---


#Testing the Tower by installing sample client&server packages

- hosts: all
  user: root
  become: true 
  gather_facts: no
  connection: ssh

  tasks:

  - name: Installing the apache web server
    apt: pkg=apache2 state=latest
    notify: Restart Apache2

  - name: Verify web server is running
    command: service apache2 status
    register: result
  - debug: var=result

  - name: Install client software - telnet
    apt: pkg=telnet state=latest
    

  handlers:
    - name: Restart Apache2
      service: name=apache2 state=restarted

